algoritmo "semnome"
// Função :
// Autor :
// Data : 04/05/2023
// Seção de Declarações 
var
a,b,c,d,x,y,z : real
inicio

//letra A
escreva("Informe a: ")
leia(a)
escreva("Informe b: ")
leia(b)
escreva("Informe c: ")
leia(c)
escreva("Informe d: ")
leia(d)
escreva("Informe y: ")
leia(y)
escreva("Informe z: ")
leia(z)

//letra A
x <- (2*a + b) / y
escreva("O valor de x é: ",x)

//letra B
x <-  4^z - 7/a
escreva("O valor de x é: ",x)




fimalgoritmo
