algoritmo "semnome"
// Função :
// Autor :
// Data : 11/05/2023
// Seção de Declarações 
var

resultado1 : real
resultado2 : real
resultado3 : real
resultado4 : real
resultado5 : real
x : real

inicio
// Seção de Comandos 

escreva("Informe o valor de x: ")
leia(x)

resultado1 <- x ^ 5

resultado2 <- resultado1 - 10

resultado3 <- resultado2 ^ 2

resultado4 <- resultado3 / 4

resultado5 <- resultado4 / 10

escreva("O resultado é: ",resultado5)


fimalgoritmo
