algoritmo "semnome"
// Função :
// Autor :
// Data : 11/05/2023
// Seção de Declarações 
var
resultado : real
distanciaMaior : real
distanciaMenor : real
inicio
// Seção de Comandos 

escreva("Informe a distancia maior: ")
leia(distanciaMaior)
escreva("Informe a distancia menor: ")
leia(distanciaMenor)

resultado <- distanciaMaior - distanciaMenor

escreva("O resultado é: ",resultado)

fimalgoritmo
