algoritmo "semnome"
// Função :
// Autor :
// Data : 16/03/2023
// Seção de Declarações 
var
num : inteiro
inicio
// Seção de Comandos 
num <- 5

escreval(num," * 1 = ",num*1)
escreval(num," * 2 = ",num*2)
escreval(num," * 3 = ",num*3)
escreval(num," * 4 = ",num*4)
escreval(num," * 5 = ",num*5)
escreval(num," * 6 = ",num*6)
escreval(num," * 7 = ",num*7)
escreval(num," * 8 = ",num*8)
escreval(num," * 9 = ",num*9)
escreval(num," * 10 = ",num*10)

fimalgoritmo
